services:
  - type: web
    name: orbidigi-scraper-name
    env: docker
    plan: free
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: ALURA_EMAIL
        value:chiaranewvlc@gmail.com
      - key: ALURA_PASS
        value: Orbidigi1314.
